[project]
name = "todo-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "fastapi[standard]>=0.139.0",
    "sqlmodel>=0.0.39",
]

[tool.ruff]
unsafe-fixes = true

[tool.ruff.lint]
select = [
    "E", "F", "UP", "B", 
    "SIM",   # Required for Example 2 (SIM401)
    "PTH",   # Required for Example 3 (PTH118)
    "RET",   # Required for Example 4 (RET505)
    "PERF",  # Required for Examples 1 & 5 (PERF401, PERF601)
]

